# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  platform: esphome

wifi:
  ap:

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi RSSI"
    id: wifi_rssi
    update_interval: 20s
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_rssi
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    icon: "mdi:wifi-strength-2"
    disabled_by_default: true

script:
  - id: tagtuner_event
    parameters:
      action: string
      uid: string
      uri: string
      artist: string
      playlist: string
    mode: queued
    max_runs: 3
    then:
      - event.trigger:
          id: tagtuner_action
          event_type: !lambda return action;
      - homeassistant.event:
          event: esphome.tagtuner
          data:
            magic: ${magic}
            action: !lambda return action;
            uid: !lambda return uid;
            uri: !lambda return uri;
            artist: !lambda return artist;
            playlist: !lambda return playlist;

event:
  - platform: template
    id: tagtuner_action
    name: "Action"
    # icon: mdi:button-pointer
    # device_class: button
    event_types:
      - clickTriple
      - clickDouble
      - clickLong
      - clickSingle
      - volumeUp
      - volumeDown
      - trackNext
      - trackPrevious
      - tagRemoved
      - tagScanned

